name: Deploy shopizer-admin app

on: workflow_dispatch

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 12.8.1

      - name: Install dependencies using npm
        run: npm install
      
      - name: Build with npm
        run: npm run build

      - name: Make dist directory
        run: mkdir shopizer-admin-dist

      - name: Copy dist directory
        run: cp -r dist shopizer-admin-dist/dist
      
      - name: Azure CLI Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy apps/shopizer-admin
        uses: azure/spring-apps-deploy@v1
        with:
          azure-subscription: ${{ vars.AZURE_SUBSCRIPTION_ID }}
          action: deploy
          service-name: ${{ vars.SPRING_APPS_SERVICE_NAME }}
          app-name: ${{ vars.SPRING_APPS_APP_NAME }}
          use-staging-deployment: false
          package: ${{ github.workspace }}/shopizer-admin-dist
          build-env: "-BP_WEB_SERVER nginx -BP_WEB_SERVER_ROOT dist -BP_WEB_SERVER_ENABLE_PUSH_STATE true"
